apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: backend
          # Using local Docker image
          image: mern_notes_app-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: dbURL
              value: "mongodb://notes-mongo:27017/notes"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
