apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
    spec:
      containers:
        - name: frontend
          # Using local Docker image
          image: mern_notes_app-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
