apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # On a real cluster you would use a cloud storage class; for local clusters we use hostPath
    path: /data/mongo
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
