apiVersion: v1
kind: Service
metadata:
  name: notes-frontend
spec:
  type: LoadBalancer
  selector:
    app: notes-frontend
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend
spec:
  selector:
    app: notes-backend
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: notes-mongo
spec:
  selector:
    app: notes-mongo
  ports:
    - port: 27017
      targetPort: 27017
